More informative exits

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -30,7 +30,11 @@ jobs:
         run: |
           PACKAGE_VERSION="$(node -p 'require("./package.json").version')"
 
-          gh release view "v${PACKAGE_VERSION}" && exit 1 || false
+          gh release view "v${PACKAGE_VERSION}" && {
+            echo "Release v${PACKAGE_VERSION} already exists!"
+            echo "::error::Release v${PACKAGE_VERSION} already exists!"
+            exit 1
+          } || false
 
           gh release create "v${PACKAGE_VERSION}" --draft --generate-notes
           echo "version=${PACKAGE_VERSION}" >> "${GITHUB_OUTPUT}"
